apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubedbs.appscode.com
spec:
  group: appscode.com
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Define your custom resource fields here
                databaseName:
                  type: string
                version:
                  type: string
                replicas:
                  type: integer
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: kubedbs
    singular: kubedb
    kind: KubeDB
    shortNames:
      - kdb
